[default]
DEBUG = false
SECRET_KEY = '1234567890'
SECURITY_TOKEN_AUTHENTICATION_KEY =  '1234567890'
CSRF_ENABLED = true
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_CONFIRMABLE = true
SECURITY_TRACKABLE = true
SECURITY_PASSWORD_SALT = 'application'
SECURITY_LOGIN_URL = '/login'
SECURITY_LOGOUT_URL = '/logout'
EXTENSIONS = [
    "app.plugins.database:init_app",
    "app.plugins.auth:init_app",
    "app.plugins.cli:init_app",
    "app.plugins.toolbar:init_app",
    "app.plugins.validation:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///app_dev.db"
SECURITY_TOKEN_AUTHENTICATION_KEY =  '1234567890'
CSRF_ENABLED = true
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_CONFIRMABLE = true
SECURITY_TRACKABLE = true
SECURITY_PASSWORD_SALT = 'application'
SECURITY_LOGIN_URL = '/login'
SECURITY_LOGOUT_URL = '/logout'
SQLALCHEMY_TRACK_MODIFICATIONS = false
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
EXTENSIONS = [
    "app.plugins.database:init_app",
    "app.plugins.auth:init_app",
    "app.plugins.cli:init_app",
    "app.plugins.toolbar:init_app",
    "app.plugins.validation:init_app",
    "app.api.routes:init_app",
]


[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
